custom:
        [
                'https://create.roblox.com/store/asset/16582923129',
                'https://github.com/Bracketed/VSDS',
                'https://www.roblox.com/groups/33845647',
        ]
